prg_comment = ""
prg_version = "0.7"
def program(prg, cmd):
    prg.add(-2500, "Na Repumper2 (+) Amp", 0, functions=dict(amplitude=lambda x: cmd.get_var('Rep_amp')))
    prg.add(-2000, "Na Repumper1 (+) Amp", 0, functions=dict(amplitude=lambda x: cmd.get_var('Rep_amp')))
    prg.add(-310, "TTL Repumper MOT ON", functions=dict(time=lambda x: x - 1e-3*cmd.get_var('Rep_pulsetime')))
    prg.add(-310, "TTL Repumper MOT OFF")
    prg.add(-310, "Pulse uw ON", functions=dict(time=lambda x: x - 1e-3*cmd.get_var('marconi1_pulsetime')), enable=False)
    prg.add(-310, "Pulse uw OFF", enable=False)
    prg.add(-305, "Trig ON Stingray z", 'atoms', enable=False)
    prg.add(-300, "Trig ON Stingray 1", 'atoms')
    prg.add(-134, "Scope 1 Trigger Pulse", polarity=1, pulse_t=0.00740, enable=False)
    prg.add(-5, "TTL Probe z ON", enable=False)
    prg.add(-5, "TTL Probe z OFF", functions=dict(time=lambda x: x + cmd.get_var('probe_pulsetime')*1e-3), enable=False)
    prg.add(0, "TTL Probe y ON")
    prg.add(0, "TTL Probe y OFF", functions=dict(time=lambda x: x + cmd.get_var('probe_pulsetime')*1e-3))
    prg.add(500, "Scope 1 Trigger ON")
    prg.add(695, "Trig OFF Stingray z", enable=False)
    prg.add(700, "Trig OFF Stingray 1")
    prg.add(1000, "Scope 1 Trigger OFF")
    prg.add(50000, "TTL Probe y OFF", functions=dict(time=lambda x: x + cmd.get_var('probe_pulsetime')*1e-3))
    prg.add(50000, "TTL Probe y ON")
    prg.add(70000, "TTL Probe y ON", enable=False)
    prg.add(70000, "TTL Probe y OFF", functions=dict(time=lambda x: x + cmd.get_var('probe_pulsetime')*1e-3), enable=False)
    prg.add(999200, "Scope 1 Trigger ON", enable=False)
    prg.add(999905, "Trig ON Stingray z", 'probe', enable=False)
    prg.add(999910, "Trig ON Stingray 1", 'probe')
    prg.add(1000000, "Scope 1 Trigger OFF", enable=False)
    prg.add(1000905, "Trig OFF Stingray z", enable=False)
    prg.add(1000910, "Trig OFF Stingray 1")
    prg.add(1001405, "TTL Probe z ON", enable=False)
    prg.add(1001405, "TTL Probe z OFF", functions=dict(time=lambda x: x + cmd.get_var('probe_pulsetime')*1e-3), enable=False)
    prg.add(1001410, "TTL Probe y ON")
    prg.add(1001410, "TTL Probe y OFF", functions=dict(time=lambda x: x + cmd.get_var('probe_pulsetime')*1e-3 * 1.8))
    prg.add(1251934, "Shutter Probe/Push Close")
    prg.add(2016024, "Trig ON Stingray z", 'dark', enable=False)
    prg.add(2016030, "Trig ON Stingray 1", 'dark')
    prg.add(2017024, "Trig OFF Stingray z", enable=False)
    prg.add(2017030, "Trig OFF Stingray 1")
    prg.add(3816025, "TTL Probe z ON", enable=False)
    prg.add(3816030, "TTL Probe y ON", enable=False)
    return prg
