prg_comment = ""
prg_version = "0.7"
def program(prg, cmd):
    prg.add(-130, "B comp x ramp", start_t=0.2, stop_x=0, n_points=200, start_x=0, stop_t=1, functions=dict(stop_t=lambda x: cmd.get_var('grad_ramp_time')+cmd.get_var('grad_ramp_time2'), stop_x=lambda x: cmd.get_var('Bx_grad_comp'), start_x=lambda x: cmd.get_var('Bx_dipole_trap'), time=lambda x: x+1e-3*cmd.get_var('marconi1_pulsetime')+1e-3*cmd.get_var('marconi1_pulsetime2')))
    prg.add(-1, "B grad x ramp", start_t=0, stop_x=0, n_points=200, start_x=0.0, stop_t=1, functions=dict(stop_t=lambda x: cmd.get_var('grad_ramp_time'), stop_x=lambda x: 2, start_x=lambda x: cmd.get_var('Bx_grad'), time=lambda x: x+1e-3*cmd.get_var('marconi1_pulsetime')+1e-3*cmd.get_var('marconi1_pulsetime2')))
    prg.add(5000, "B grad x ramp", start_t=0, stop_x=0, n_points=200, start_x=0, stop_t=0, functions=dict(stop_t=lambda x: cmd.get_var('grad_ramp_time2'), stop_x=lambda x: 8, start_x=lambda x: 2, time=lambda x: x+1e-3*cmd.get_var('marconi1_pulsetime')+1e-3*cmd.get_var('marconi1_pulsetime2')+cmd.get_var('grad_ramp_time')))
    prg.add(11000, "B grad x ramp", start_t=0, stop_x=0, n_points=200, start_x=0, stop_t=0, functions=dict(stop_t=lambda x: cmd.get_var('grad_ramp_time2'), stop_x=lambda x: 2, start_x=lambda x: 8, time=lambda x: x+1e-3*cmd.get_var('marconi1_pulsetime')+1e-3*cmd.get_var('marconi1_pulsetime2')+cmd.get_var('grad_ramp_time')+cmd.get_var('grad_ramp_time2')))
    prg.add(15000, "B grad x ramp", start_t=0, stop_x=0, n_points=200, start_x=0, stop_t=0, functions=dict(stop_t=lambda x: cmd.get_var('grad_ramp_time'), stop_x=lambda x: 1.03, start_x=lambda x: 2, time=lambda x: x+1e-3*cmd.get_var('marconi1_pulsetime')+1e-3*cmd.get_var('marconi1_pulsetime2')+cmd.get_var('grad_ramp_time')+cmd.get_var('grad_ramp_time2')*2))
    prg.add(16000, "B comp x ramp", start_t=0, stop_x=0, n_points=200, start_x=0, stop_t=0, functions=dict(stop_t=lambda x: cmd.get_var('grad_ramp_time')+cmd.get_var('grad_ramp_time2'), stop_x=lambda x: cmd.get_var('Bx_comp_after_ramp'), start_x=lambda x: cmd.get_var('Bx_grad_comp'), time=lambda x: x+1e-3*cmd.get_var('marconi1_pulsetime')+1e-3*cmd.get_var('marconi1_pulsetime2')+cmd.get_var('grad_ramp_time')+cmd.get_var('grad_ramp_time2')))
    return prg
